name: Flutter Release Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"
      - name: Clean build
        run: flutter clean
      - name: Get dependencies
        run: flutter pub get
      - name: Build Debug APK
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
