name: Android Debug

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          cache: "gradle"
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: "stable"
          cache: true
      - name: Clean build
        run: flutter clean
      - name: Get dependencies
        run: flutter pub get
      - name: Start APK build
        run: flutter build apk --debug --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
